# -*- coding: utf-8 -*-
"""atividade 1 python_ebac

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cc9iYLQiplJ-nKENOxmDpO1H-y2iEQEC
"""

continuar = "s"

while continuar.lower() == "s": # loop com while

# comandos input para receber os valores do usuário
    num1 = int(input("Olá, digite um valor a ser calculado: "))
    print(num1)

    num2 = int(input("\nDigite o segundo valor a ser calculado: "))


#opções de operações matemáticas que o usuário tem disponível
    print("\nEscolha a operação que deseja realizar:")
    print("1- Adição")
    print("2- Subtração")
    print("3- Multiplicação")
    print("4- Divisão")

    operacao = int(input("Digite o número da operação desejada: "))


# condicionais
    if operacao == 1:
        resultado = num1 + num2
        print(f"O resultado da adição é {resultado}")

    elif operacao == 2:
        resultado = num1 - num2
        print(f"O resultado da subtração é {resultado}")

    elif operacao == 3:
        resultado = num1 * num2
        print(f"O resultado da multiplicação é {resultado}")

    elif operacao == 4:
        if num2 != 0:
            resultado = num1 / num2
            print(f"O resultado da divisão é {resultado}")
        else:
            print("Não é possível dividir por zero!")

    else:
        print("Opção inválida, tente novamente!")

# operação que permite ao usuário realizar novas operações
#sem sair do programa.
    continuar = input("Deseja fazer outra operação? (s/n): ")